### PR TITLE
Fix unhandled exception when deleting the last server

### LINKED ISSUE #80: Exception occurs if all servers are deleted
Just a nitpick, but shvspy crashes with this exception if you delete all server nodes.

```bash
2025-06-23T07:30:02[exception.cpp:37]|E| SHV_EXCEPTION: /build/yjhj7nflmsasaxrh71wii6b7cjx32i0b-source/shvspy/src/servertreemodel/shvnodeitem.cpp:109 ServerNode parent must exist.
terminate called after throwing an instance of 'shv::core::Exception'
  what():  ServerNode parent must exist.
Aborted
```

### PR DESCRIPTION
**Pull request by syyyr**
Fixes #80

### CODE REVIEW

File: shvspy/src/mainwindow.cpp [hunk 1]
```diff
@@ -679,6 +679,12 @@ void MainWindow::onNotificationsDoubleClicked(const QModelIndex &ix)
 void MainWindow::onShvTreeViewCurrentSelectionChanged(const QModelIndex &curr_ix, const QModelIndex &prev_ix)
 {
 	Q_UNUSED(prev_ix)
+
+	// This happens when you delete the last server in the server tree.
+	if (curr_ix.row() == -1 && curr_ix.column() == -1) {
```
Comment (fvacek) [inline shvspy/src/mainwindow.cpp:684]:
```suggestion
	if (!curr_ix.isValid()) {
```
